"""Agrega modelo Capitulo y relación con Autor

Revision ID: 73867818f482
Revises: fbceb35ecdb2
Create Date: 2025-08-06 11:38:21.455198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73867818f482'
down_revision = 'fbceb35ecdb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capitulo_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'capitulo', ['capitulo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('capitulo_id')

    # ### end Alembic commands ###
