"""Add obra_id to Autor

Revision ID: fbceb35ecdb2
Revises: 
Create Date: 2025-08-06 10:57:17.280280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbceb35ecdb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('obra_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rol_obra', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('huella_digital', sa.String(length=300), nullable=True))
        batch_op.create_foreign_key(None, 'obra', ['obra_id'], ['id'])
        batch_op.drop_column('seudonimo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seudonimo', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('huella_digital')
        batch_op.drop_column('rol_obra')
        batch_op.drop_column('obra_id')

    # ### end Alembic commands ###
